[barrel]
fly_time = 1.5
respawn_time = 2.0

[kick]
minimal_time = 0.2
maximal_time = 3

[basket]
min_area = 50
hsv_min = [5, 42, 244]
hsv_max = [29, 156, 255]

border_setup_time = 5.0
left_border_tolirance = 50
axis_line_gap = [0.4, 0.6] 
position_count = 20
velocity_checking_time = 0.2

[basced.blur]
ksize = [15, 15]
deltax = 30
threshold = 15

[display]
resolution = [1920, 1080]
debug_view = false
