[barrel]
fly_time = 1.2
respawn_time = 2

[kick]
kicking_detection_sensitivity = 0.6
barrel_boucing_time = 0.1
minimal_kick_delay = 1.5

[basket]
min_area = 500
hsv_min = [5, 32, 234]
hsv_max = [49, 166, 255]

border_setup_time = 5.0
border_tolirance = 25
axis_line_gap = [0.4, 0.6] 
position_count = 0.2
velocity_checking_time = 0.25

[basced.blur]
ksize = [15, 15]
deltax = 30
threshold = 15

[display]
# resolution = [3840,2160]
resolution = [1920,1080]
debug_view = true

[program]
start_key = 'ctrl+p'