[detectors.ai]
model_path = "./assets/best.onnx" 

score_threshold = 0.2
iou_threshold = 0.2
model_size = 160

[kick_manager]
template_path = "assets/kick_label_2160x1440.png"
template_detection_sensitivity = 0.4
barrel_bouncing_time = 0.5

[basket_predictor]
border_tolirance = 0.1
direction_detection_time = 0.1
border_setup_time = 5
barrel_fly_time = 2.35
velocity_setup_position = 0.25
max_time = 4.5

[display]
basket_y_gap = 0.7 # Bigger - Faster
debug_view = true
debug_video = false
debug_view_scalling = 1

[program]
monitor_id = 0
window_title = "Deep Rock Galactic"  
start_key = 'ctrl+p'
stop_key = 'ctrl+p'
