[barrel]
fly_time = 1.55
respawn_time = 2

[detectors.hsv]
min_area = 200
hsv_min = [5, 32, 234]
hsv_max = [49, 166, 255]

ksize = [5, 5]
sigma_x = 3
threshold = 30

[detectors.ai]
model_path = "D:\\Python\\Yolov8-Model-Training\\runs\\detect\\train3\\weights\\best.pt"
classes_path = 'd:/Python/Yolov8-Model-Training/dataset/classes.txt'

score_threshold = 0.1
iou_threshold = 0.1
# target_size = 704
target_size = 320
# target_size = 224

[detectors.difference]
min_area = 300

ksize = [11, 11]
sigma_x = 11
threshold = 5

[detectors.point]
point1_position = [300, 250]
point2_position = [800, 250]
position_margin = 15
basket_color = [232, 255, 255]
color_margin = 230
basket_width = 50

[kick_manager]
template_path = "assets/e_button_1920x1080.png"
template_detection_sensitivity = 0.8
barrel_bouncing_time = 0.3
minimal_kick_delay = 1

[kick]
kicking_detection_sensitivity = 0.3
minimal_kick_delay = 1.5

[basket_predictor]
time_of_positions = 0.4
border_tolirance = 50
border_setup_time = 5.0
velocity_checking_time = 0.3

[display]
resolution = [1920,1080]
basket_y_gap = [0 ,700]
debug_view = false

[program]
start_key = 'ctrl+p'