[detectors.ai]
model_path = "D:\\Python\\Yolov8-Model-Training\\runs\\detect\\train6\\weights\\best.pt" 

score_threshold = 0.3
iou_threshold = 0.3
model_size = 320

[kick_manager]
template_path = "assets/e_button_1920x1080.png"
template_detection_sensitivity = 0.4
barrel_bouncing_time = 0.35

[basket_predictor]
border_tolirance = 0.013
border_setup_time = 4.0
barrel_fly_time = 2.4
velocity_setup_position = 0.3

[display]
basket_y_gap = 0.3
debug_view = true
debug_view_resolution = [800, 600]

[program]
monitor_id = 0
window_title = "Deep Rock Galactic"  
start_key = 'ctrl+p'